ports:
  - port: 3333
  - port: 3000
    onOpen: open-preview
tasks:
  - init: cd web
    command: nvm install 13.3.0 && yarn install && yarn start
  - init: cd ../backend
    command: yarn install && yarn dev
